#!/bin/bash

# The --profile argument uses this profile:
# General->Profile name: Timer
# General->Command: /bin/bash
# General->Columns: 13
# General->Rows: 2
# Appearance->Color Scheme: Black on White
# Appearance->Font: Monospace, Text size: 24
# Scrolling->Scroll Bar: Hide
# Advanced->Cursor->Custom cursor color: white (#fff)

kon_opts="--hold --profile Timer --hide-menubar --hide-tabbar -p ScrollBarPosition=2 -p TerminalRows=2 -p TerminalColumns=13"
# --hold keeps the terminal window open after the command exits.

if [ $# -lt 2 ]
then
	echo "timer-gui: need arguments"
	exit 1
fi

konsole 2>/dev/null $kon_opts -e timer "$@"
